In [1]:
!pip install yfinance pandas requests beautifulsoup4 lxml plotly

Requirement already satisfied: yfinance in c:\users\sssuj\anaconda3\lib\site-packages (1.4.1)
Requirement already satisfied: pandas in c:\users\sssuj\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: requests in c:\users\sssuj\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\sssuj\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: lxml in c:\users\sssuj\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: plotly in c:\users\sssuj\anaconda3\lib\site-packages (6.3.0)
Requirement already satisfied: numpy>=1.16.5 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (4.0.6)
Requirement already satisfied: curl_cffi>=0.15 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\sssuj\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sssuj\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sssuj\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sssuj\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sssuj\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sssuj\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sssuj\anaconda3\lib\site-packages (from requests) (2026.5.20)
Requirement already satisfied: soupsieve>1.2 in c:\users\sssuj\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\sssuj\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\sssuj\anaconda3\lib\site-packages (from plotly) (2.7.0)
Requirement already satisfied: packaging in c:\users\sssuj\anaconda3\lib\site-packages (from plotly) (25.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\sssuj\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: rich in c:\users\sssuj\anaconda3\lib\site-packages (from curl_cffi>=0.15->yfinance) (14.2.0)
Requirement already satisfied: pycparser in c:\users\sssuj\anaconda3\lib\site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in c:\users\sssuj\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\sssuj\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\sssuj\anaconda3\lib\site-packages (from rich->curl_cffi>=0.15->yfinance) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\sssuj\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.15->yfinance) (0.1.2)

In [2]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
tesla = yf.Ticker("TSLA")

tesla_data = tesla.history(period="max")

tesla_data.reset_index(inplace=True)

tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [4]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

html_data = requests.get(url).text

soup = BeautifulSoup(html_data, "html.parser")

tables = pd.read_html(str(soup))

tesla_revenue = tables[1]

tesla_revenue.columns = ["Date", "Revenue"]

tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(",", "")
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace("$", "", regex=False)

tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue["Revenue"] != ""]

tesla_revenue.tail()

C:\Users\sssuj\AppData\Local\Temp\ipykernel_24020\3029815199.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(str(soup))

          Date Revenue
48  2010-09-30      31
49  2010-06-30      28
50  2010-03-31      21
52  2009-09-30      46
53  2009-06-30      27

In [5]:
gme = yf.Ticker("GME")

gme_data = gme.history(period="max")

gme_data.reset_index(inplace=True)

gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693350,1.603296,1.691666,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683250,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683250,1.687458,1.658001,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [6]:
import requests
import pandas as pd

url = "https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

tables = pd.read_html(html)

print("Tables found:", len(tables))

for i, table in enumerate(tables[:5]):
    print("\nTable", i)
    print(table.head())

Tables found: 4

Table 0
   GameStop Annual Revenue (Millions of US $)  \
0                                        2026
1                                        2025
2                                        2024
3                                        2023
4                                        2022

  GameStop Annual Revenue (Millions of US $).1
0                                       $3,630
1                                       $3,823
2                                       $5,273
3                                       $5,927
4                                       $6,011

Table 1
  GameStop Quarterly Revenue (Millions of US $)  \
0                                    2026-01-31
1                                    2025-10-31
2                                    2025-07-31
3                                    2025-04-30
4                                    2025-01-31

  GameStop Quarterly Revenue (Millions of US $).1
0                                          $1,104
1                                            $821
2                                            $972
3                                            $732
4                                          $1,283

Table 2
                                              Sector  \
0                             Consumer Discretionary
1  GameStop Corp. offers the best selection of ne...

                                            Industry  \
0                                             Gaming
1  GameStop Corp. offers the best selection of ne...

                                          Market Cap  \
0                                           $10.411B
1  GameStop Corp. offers the best selection of ne...

                                             Revenue
0                                            $3.630B
1  GameStop Corp. offers the best selection of ne...

Table 3
                             Stock Name        Country Market Cap  PE Ratio
0                      Nintendo (NTDOY)          Japan   $66.938B     25.00
1                  Electronic Arts (EA)  United States   $50.736B     35.57
2                         Roblox (RBLX)  United States   $36.780B      0.00
3  Take-Two Interactive Software (TTWO)  United States   $36.493B     65.04
4                 Las Vegas Sands (LVS)  United States   $35.470B     17.76

C:\Users\sssuj\AppData\Local\Temp\ipykernel_24020\1948077956.py:12: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(html)

In [7]:
gme_revenue = tables[1]

gme_revenue.columns = ["Date", "Revenue"]

gme_revenue["Revenue"] = gme_revenue["Revenue"].astype(str)
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace(",", "")
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace("$", "", regex=False)

gme_revenue.tail()

          Date Revenue
54  2012-07-31    1550
55  2012-04-30    2002
56  2012-01-31    3579
57  2011-10-31    1947
58  2011-07-31    1744

In [8]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def make_graph(stock_data, revenue_data, stock):

    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Historical Share Price", "Historical Revenue")
    )

    fig.add_trace(
        go.Scatter(
            x=stock_data['Date'],
            y=stock_data['Close'],
            name="Share Price"
        ),
        row=1,
        col=1
    )

    revenue_data["Revenue"] = revenue_data["Revenue"].astype(float)

    fig.add_trace(
        go.Scatter(
            x=revenue_data["Date"],
            y=revenue_data["Revenue"],
            name="Revenue"
        ),
        row=2,
        col=1
    )

    fig.update_layout(
        title=stock,
        height=800,
        showlegend=False
    )

    fig.show()

In [9]:
make_graph(tesla_data, tesla_revenue, "Tesla")

In [10]:
make_graph(gme_data, gme_revenue, "GameStop")